//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : test
	/// Data Source    : 127.0.0.1
	/// Server Version : 5.5.5-10.4.8-MariaDB
	/// </summary>
	public partial class TestDB : LinqToDB.Data.DataConnection
	{
		public ITable<Comboboxitemname> Comboboxitemnames { get { return this.GetTable<Comboboxitemname>(); } }
		public ITable<Comboboxname>     Comboboxnames     { get { return this.GetTable<Comboboxname>(); } }

		public TestDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public TestDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("comboboxitemname")]
	public partial class Comboboxitemname
	{
		[PrimaryKey, Identity] public int    Id             { get; set; } // int(11)
		[Column,     NotNull ] public string Name           { get; set; } // varchar(250)
		[Column,     NotNull ] public int    ComboBoxNameId { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// FK_ITEM_NAME
		/// </summary>
		[Association(ThisKey="ComboBoxNameId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_ITEM_NAME", BackReferenceName="Itemnames")]
		public Comboboxname ComboBoxName { get; set; }

		#endregion
	}

	[Table("comboboxname")]
	public partial class Comboboxname
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // int(11)
		[Column,     NotNull ] public string Name { get; set; } // varchar(150)

		#region Associations

		/// <summary>
		/// FK_ITEM_NAME_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ComboBoxNameId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Comboboxitemname> Itemnames { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Comboboxitemname Find(this ITable<Comboboxitemname> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Comboboxname Find(this ITable<Comboboxname> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
